# ==== black ====
[tool.black]
line-length = 119
target-version = ['py312']

# ==== isort ====
[tool.isort]
profile = "black"
line_length = 119
skip_glob = ["**/migrations/*.py"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "store.settings"
